language: d
dist: bionic

d:
  - dmd
  - ldc

before_install:
  - sudo ./.travis-install-openssl.sh

script:
  - dub build --compiler=${DC}
  - dub build --compiler=${DC} --root=example
  - dub build --compiler=${DC} --root=test
